### ISSUE TITLE
composer: package talesoft/tale-jade-laravel could not be found in any version

### ISSUE THREAD

**Issue by Riant** [Talesoft/tale-jade-laravel#1]
The requested package talesoft/tale-jade-laravel could not be found in any version, there may be a typo in the package name.

And when I search "talesoft/tale-jade" on https://packagist.org/search/?q=tale-jade-laravel,  I only got **talesoft/tale-jade**

Thanks.

**Comment by TorbenKoehn** [comment]
Can you try it again please? :)

**Comment by Riant** [comment]
Thanks very much.
