### ISSUE TITLE
Fresh install, Laravel 5.2, error:

### ISSUE THREAD

**Issue by terion-name** [Talesoft/tale-jade-laravel#2]
```
ErrorException in Renderer.php line 147:
Undefined property: Tale\Jade\Renderer::$_options
```

![2016-03-06 19 35 09](https://cloud.githubusercontent.com/assets/1060205/13555806/8f75ebee-e3d2-11e5-8409-3af4af8b7a92.png)

**Comment by TorbenKoehn** [comment]
Hello,

this should be fixed by now, can you update your composer files and test it?

Make sure that it uses any Tale Jade version above 1.4.1, 1.4.2 will probably work like a charm.
