### ISSUE TITLE
Error after 1.4.3 update

### ISSUE THREAD

**Issue by vr55** [Talesoft/tale-jade-laravel#3]
I have this error after 1.4.3 update
![2016-05-24 22 35 03](https://cloud.githubusercontent.com/assets/15677169/15517375/140c579c-2200-11e6-8b25-e8ba84365c3d.png)

**Comment by TorbenKoehn** [comment]
Yep, I'll write a fix today! Sorry for the inconvenience

**Comment by TorbenKoehn** [comment]
Hey, I updated the laravel brige to Tale Jade 1.4.4 now. Can you test it?

**Comment by vr55** [comment]
Hello. I've tested and everything is ok now. Thank you)
