### ISSUE TITLE
Facades are mistaken with filters.

### ISSUE THREAD

**Issue by imanghafoori1** [Talesoft/tale-jade-laravel#4]
The question is how to convert this to jade equivalent:
@if (Route::has('login'))
@endif

**Comment by imanghafoori1** [comment]
the Answer is 
-if (Route::has('login'))

**Comment by TorbenKoehn** [comment]
Even better is:

``` jade

if Route::has('login')
    p Whatever

```

Jade has native IF-syntax!

You can find more information at http://jade.talesoft.codes :)

**Comment by imanghafoori1** [comment]
I think that does not work because :: facade colons are mistaken with jade filters.

**Comment by TorbenKoehn** [comment]
This is actually a bug then! Thanks for finding it.

You can surround any expression with parentheses to make sure it's rendered correctly.

``` jade
if (Route::has('login'))
    p Whatever
```

This works [for sure](http://sandbox.jade.talesoft.codes/id-57f659dd7b6ea.html) :)

**Comment by imanghafoori1** [comment]
This code 
`
if (Route::has('login'))
    p Whatever
`
is equivalent to this
`
-if (Route::has('login')){
    p Whatever
-}
`
in fact it is better to use the first

**Comment by TorbenKoehn** [comment]
The first is indeed better, it simply translates to the same as the second.

`-` indicates _raw code_ while the first is native Jade syntax (and you don't have to close the loop manually)

I will fix the `::`-bug (I know exactly what causes the problem) and after that you'll be able to simply use

``` jade
if Route::has('login')
    p Whatever
```

I'll update this when I'm done (might take a week or two, I am quite busy currently)

**Comment by imanghafoori1** [comment]
I can not write spaces and line breaks within my code... sorry for that.

**Comment by imanghafoori1** [comment]
But it seems that you got what I meant.
good luck

**Comment by TorbenKoehn** [comment]
Use block code highlighting, it's a markdown syntax

https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Three backticks instead of one to indicate the start and end, write `jade` after the first 3 backticks to highlight with Jade-syntax :)
